name: Build URL Shortener - Golang

on:
  push:
    branches:
      - master
  paths:
    - ./services/url-shortener

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Build
        run: go build -o main
