name: Build Hello World - Node.js

on:
  push:
    branches:
      - master
    paths:
      - 'services/hello-world-nodejs/*'
  pull_request:
    branches:
      - master
    paths:
      - 'services/hello-world-nodejs/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: use nodejs
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./services/hello-world-nodejs
      - name: Build TypeScript
        run: yarn build
        working-directory: ./services/hello-world-nodejs
