name: Against Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Build Golang
        uses: ../../services/url-shortener/actions
      - name: Build
        uses: ../../services/hello-world-nodejs/actions
