name: Build Hello World - Node.js

on:
  push:
    branches:
      - master
    paths:
      - ./services/hello-world-nodejs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: use nodejs
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build TypeScript
        run: yarn build
    # TODO: Push to docker registry

